// Generated by https://quicktype.io

export interface Content {
    initDate:      Date;
    id:            number;
    name:          string;
    address:       string;
    zipCode:       string;
    city:          string;
    country:       string;
    email:         string;
    phone:         string;
    mobile:        string;
    www:           string;
    latitude:      string;
    longitude:     string;
    fileName:      string;
    rootType:      string;
    bookingOnline: string;
    required:      boolean;
    company:       Company;
    texts:         Text[];
    attributes:    any[];
    photos:        any[];
    profiles:      any[];
}

export interface Company {
}

export interface Text {
    textId:   number;
    language: string;
    type:     string;
    text:     string;
}
